[project]
name = "pipeline_api"
version = "0.1.0"
description = ""
authors = [
    {name = "rpw1134",email = "ryanw1134@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.121.2,<0.122.0)",
    "uvicorn (>=0.38.0,<0.39.0)",
    "unstructured[pdf] (>=0.18.18,<0.19.0)",
    "pymupdf (>=1.26.6,<2.0.0)",
]

[tool.poetry]
packages = [{include = "pipeline_api", from = "src"}]

[tool.poetry.scripts]
dev = "pipeline_api.scripts.dev:dev"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
